### PR TITLE
added my islandinthenet.com doamin

### PR DESCRIPTION
**Pull request by khurtwilliams**
added my islandinthenet.com domain

### CODE REVIEW

**Comment by snarfed** [comment]
wow, just now noticed that i misse this. sorry about that!

**Comment by snarfed** [comment]
happy to merge still if you want to resolve conflicts first.

**Comment by khurtwilliams** [comment]
I'm not sure where the conflict is.

**Comment by snarfed** [comment]
github doesn't have a browser-based three-way merge conflict resolution tool; you'd need to use the command line or your own local clone of the repo. if you don't want to do that, you can just close this and make your change again, from head. that should work without any conflicts.

**Pull request closed without merging**
